REM USUARIO DEL APLICATIVO FS_SGC_US

drop user FS_SGC_US cascade;

Create user FS_SGC_US
 Identified by fs_sgc_us
 Default tablespace TS_DSGC
 Temporary tablespace TS_TSGC    
 account unlock;


Grant 
  ALTER USER, CREATE CLUSTER, CREATE DATABASE LINK, CREATE PROFILE , ALTER PROFILE, 
  CREATE PROCEDURE, CREATE PUBLIC DATABASE LINK, 
  CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, 
  CREATE SESSION, CREATE SYNONYM, CREATE TABLE, 
  CREATE TRIGGER, CREATE USER , CREATE VIEW, CREATE TYPE,
  DROP PUBLIC SYNONYM, EXECUTE ANY PROCEDURE, 
  SELECT ANY SEQUENCE, SELECT ANY TABLE, 
  UNLIMITED TABLESPACE to FS_SGC_US;
