--
PROMPT
PROMPT CREANDO TABLA GE_TUSER
PROMPT
--
CREATE TABLE OWNK_US.GE_TUSER
{
    USER_USER   VARCHAR2(100)           CONSTRAINT NN_GE_TUSER_USER NOT NULL;
    USER_NAME   VARCHAR2(50)            CONSTRAINT NN_GE_TUSER_NAME NOT NULL;
    USER_NICK   VARCHAR2(50)            CONSTRAINT NN_GE_TUSER_NICK NOT NULL;
    USER_ESTA   VARCHAR2(50)            CONSTRAINT NN_GE_TUSER_ESTA NOT NULL;
}

COMMENT ON TABLE OWNK_US.GE_TUSER IS 'Tabla de usuarios';
COMMENT ON COLUMN GE_TUSER.USER_USER IS 'Identificador del usuario';
COMMENT ON COLUMN GE_TUSER.USER_NAME IS 'Nombre del usuario'; 
COMMENT ON COLUMN GE_TUSER.USER_NICK IS 'Nickname del usuario';
COMMENT ON COLUMN GE_TUSER.USER_ESTA IS 'Identificador de estado';

TABLESPACE TS_DOWNK
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;