REM ******************************************************************
REM Fecha         : 26/07/2017
REM Realizado por : Ownk
REM Base de Datos : FS_SGC_US
REM ******************************************************************


REM TABLESPACE TEMPORAL

Create Temporary tablespace TS_TOWNK TEMPFILE
'C:\app\OWNK\product\18.0.0\oradata\XE\TOWNK.dbf' size 300m
         Extent management local uniform size 2m
;


REM TABLESPACE DE DATOS

CREATE TABLESPACE TS_DOWNK DATAFILE 
  'C:\app\OWNK\product\18.0.0\oradata\XE\DOWNK.DBF' SIZE 300M AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


REM TABLESPACE DE INDICES 
                                                            
CREATE TABLESPACE TS_IOWNK DATAFILE 
  'C:\app\OWNK\product\18.0.0\oradata\XE\IOWNK.DBF' SIZE 300M AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;   

