REM USUARIO DEL APLICATIVO OWNK_US

alter session set "_ORACLE_SCRIPT"=true;

drop user OWNK_US cascade;

Create user OWNK_US
 Identified by OWNK_US
 Default tablespace TS_DOWNK
 Temporary tablespace TS_TOWNK    
 account unlock;


Grant 
  ALTER USER, CREATE CLUSTER, CREATE DATABASE LINK, CREATE PROFILE , ALTER PROFILE, 
  CREATE PROCEDURE, CREATE PUBLIC DATABASE LINK, 
  CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, 
  CREATE SESSION, CREATE SYNONYM, CREATE TABLE, 
  CREATE TRIGGER, CREATE USER , CREATE VIEW, CREATE TYPE,
  DROP PUBLIC SYNONYM, EXECUTE ANY PROCEDURE, 
  SELECT ANY SEQUENCE, SELECT ANY TABLE, 
  UNLIMITED TABLESPACE to OWNK_US;
