
INSERT INTO "OWNK_US"."GE_TUSER" (USER_USER, USER_NAME, USER_NICK, USER_ESTA) VALUES ('1', 'user1', 'nick1', 'A');
INSERT INTO "OWNK_US"."GE_TUSER" (USER_USER, USER_NAME, USER_NICK, USER_ESTA) VALUES ('2', 'user2', 'nick2', 'B');
INSERT INTO "OWNK_US"."GE_TUSER" (USER_USER, USER_NAME, USER_NICK, USER_ESTA) VALUES ('3', 'user3', 'nick3', 'C');
INSERT INTO "OWNK_US"."GE_TUSER" (USER_USER, USER_NAME, USER_NICK, USER_ESTA) VALUES ('4', 'user4', 'nick4', 'D');
COMMIT;