INSERT INTO "OWNK_US"."GE_TESTA" (ESTA_ESTA, ESTA_DESC) VALUES ('A', 'Activo');
INSERT INTO "OWNK_US"."GE_TESTA" (ESTA_ESTA, ESTA_DESC) VALUES ('B', 'Bloqueado');
INSERT INTO "OWNK_US"."GE_TESTA" (ESTA_ESTA, ESTA_DESC) VALUES ('C', 'Cansado');
INSERT INTO "OWNK_US"."GE_TESTA" (ESTA_ESTA, ESTA_DESC) VALUES ('D', 'Drogrado');

COMMIT;