--
-- Foreign Key Constraints for Table GE_TUSER
--

PROMPT
PROMPT CREANDO LLAVE FORANEA GE_TUSER CON GE_TESTA
PROMPT

ALTER TABLE GE_TUSER ADD (
CONSTRAINT FK_GE_TUSER_GE_TESTA FOREIGN KEY (USER_ESTA)
REFERENCES GE_TESTA (ESTA_ESTA)
TABLESPACE TS_IOWNK);

