--
-- Primary Key Constraints for Table GE_TUSER
--

PROMPT
PROMPT CREANDO LLAVE PRIMARIA GE_TUSER
PROMPT

ALTER TABLE GE_TUSER ADD (
CONSTRAINT PK_GE_TUSER PRIMARY KEY (USER_USER)
USING INDEX
TABLESPACE TS_IOWNK);