--
-- Primary Key Constraints for Table GE_TESTA
--

PROMPT
PROMPT CREANDO LLAVE PRIMARIA GE_TESTA
PROMPT

ALTER TABLE GE_TESTA ADD (
CONSTRAINT PK_GE_TESTA PRIMARY KEY (ESTA_ESTA)
USING INDEX
TABLESPACE TS_IOWNK);